config/routes.rb
Rails.application.routes.draw do
	root to: 'pages#home'
	devise_for :users, controllers: {
		registrations: 'users/registrations'
	}
	get 'about', to:'pages#about'
	resources :contacts, only: :create
	get 'contact-me', to:'contacts#new', as: 'new_contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
	self.abstract_class = true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	
	# Contact form validation
	validates :name, presence: true
	validates :email, presence: true
	validates :comments, presence: true
end

app/models/plan.rb
class Plan < ActiveRecord::Base
	has_many :users
end

app/models/user.rb
class User < ApplicationRecord
	# Include default devise modules
	# Others available are: :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
			:recoverable, :rememberable, :trackable, :validatable

	belongs_to :plan

	# If valid form fields, Stripe sets up a subscription for customer
	attr_accessor :stripe_card_token
	def save_with_subscription
		if valid?
			customer = Stripe::Customer.create(description: email, plan: plan_id, card: stripe_card_token)
			self.stripe_customer_token = customer.id
			save!
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

	# Whitelist form fields to be processed if coming from a devise sign up form
	before_action :configure_permitted_parameters, if: :devise_controller?

	protected
		def configure_permitted_parameters
			devise_parameter_sanitizer.permit(:sign_up) {
				|u| u.permit(:stripe_card_token, :email, :password, :password_confirmation)
			}
		end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	
	# GET request to /contact-me
	def new
		@contact = Contact.new
	end
	
	# POST request for /contacts
	def create
		@contact = Contact.new(contact_params)
		if @contact.save
			name = params[:contact][:name]
			email = params[:contact][:email]
			comment = params[:contact][:comments]
			ContactMailer.contact_email(name, email, comment).deliver
			flash[:success] = "Successfully sent message!"
			redirect_to new_contact_path
		else
			flash[:danger] = @contact.errors.full_messages.join(", ")
			redirect_to new_contact_path
		end
	end
	
	private
		# Strong parameters and whitelisting for form fields
		def contact_params
			params.require(:contact).permit(:name, :email, :comments)
		end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	# GET request for / -> home page
	def home
		@base_plan = Plan.find(1)
		@pro_plan = Plan.find(2)
	end

	def about

	end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
	before_action :select_plan, only: :new

	# Extend default Devise gem behavior so subscription users are accounted for
	def create
		super do |resource|
			if params[:plan]
				resource.plan_id = params[:plan]
				if resource.plan_id == 2
					resource.save_with_subscription
				else
					resource.save
				end
			end
		end
	end

	private
		def select_plan
			unless (params[:plan] == '1' || params[:plan] == '2')
				flash[:notice] = "Please select a valid membership plan to sign up."
				redirect_to root_url
			end
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<div class="container">
	<div class="row">
		<h3 class = text-center>Contact Me</h3>
		
		<div class="col-md-4 col-md-offset-4">
			<div class="well">
				<%= form_for @contact do |f| %>
					<div class="form-group">
						<%= f.label :name %>
						<%= f.text_field :name, class: 'form-control' %>
					</div>
					<div class="form-group">
						<%= f.label :email %>
						<%= f.text_field :email, class: 'form-control' %>
					</div>
					<div class="form-group">
						<%= f.label :comments %>
						<%= f.text_area :comments, class: 'form-control' %>
					</div>
					<%= f.submit 'Submit', class: 'btn-default' %>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>PetFinder</title>
		<%= csrf_meta_tags %>
		<link href="//fonts.googleapis.com/css?family=Open+Sans:400,700i,800|Roboto" rel="stylesheet">
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag "https://js.stripe.com/v2/", type: 'text/javascript' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
		<%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
	</head>

	<body>
		<nav class="navbar navbar-default navbar-static-top" role="navigation">
			<div class='container'>
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<%= link_to root_path, class: "navbar-brand" do %> <!-- <a href="/" class="navbar-brand"><i class="fa fa-group"></i> SaaS Prototype </a> -->
						<i class="fa fa-paw"></i>
						PetFinder
					<% end %>
				</div>
				<div class="collapse navbar-collapse" id="main-nav-collapse">
					<div class="nav navbar-nav navbar-right">
						<% if user_signed_in? %>
							<%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "btn btn-default navbar-btn" %>
						<% else %>
							<%= link_to "Log In", new_user_session_path, class: "btn btn-default navbar-btn" %> <!-- <a href="/users/sign_in" class="btn btn-default navbar-btn">Log In</a> -->
						<% end %>
					</div>
					<ul class="nav navbar-nav navbar-right">
						<li><%= link_to "About", about_path %></li>  <!-- <li><a href="/about"> About </a></li> -->
						<li><%= link_to "Contact", new_contact_path %></li>
					</ul>
				</div><!-- /.navbar-collapse -->
			</div>
		</nav>

		<div class="container flash-container">
			<% flash.each do |type, msg| %>
					<%= content_tag :div, msg, class: "alert alert-#{type}" %>
			<% end %>
		</div>

		<%= yield %>

	</body>
</html>

app/views/pages/about.html.erb
<div class="container text-center">
	<h1>ABOUT PAGE!</h1>
	<p>My name is Jordan and I am learning stuff.</p>
	Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe, tenetur, est porro ea dolores corrupti provident commodi nobis deserunt inventore eligendi ut expedita aliquam nihil reprehenderit neque quam totam qui.
</div>

app/views/pages/home.html.erb
<div class="home-page text-center container-fluid">
	<h1>Welcome to the SaaS prototype site!</h1>
	<h3>A site where possibilities are unlimited.</h3>
</div>

<div class="container home-signup-links">
	<div class="row">

		<div class="col-md-6">
			<div class="well">
				<h2 class="text-center">Basic Membership</h2>
				<h4 class="text-center">Sign up for free account</h4>
				<ul class="center">
					<li>Get simple access</li>
				</ul>
				<%= link_to "Sign up with Basic", new_user_registration_path(plan: @base_plan.id), class: 'btn btn-primary btn-lg btn-block' %>
			</div>
		</div>

		<div class="col-md-6">
			<div class="well">
				<h2 class="text-center">Pro Membership</h2>
				<h4 class="text-center">Sign up for the pro account for $0.01/month</h4>
				<ul class="center">
					<li>Get access to information</li>
				</ul>
				<%= link_to "Sign up with Pro", new_user_registration_path(plan: @pro_plan.id), class: 'btn btn-success btn-lg btn-block' %>
			</div>
		</div>
	</div>
</div>